<?php

// bootstrap.php generated by CarteBlanche

namespace AboutMde\Bootstrap;
use \CarteBlanche\App\Bootstrap\SafeBootstrap;
class ContainerBootstrap extends SafeBootstrap {

    protected $bundles = array(
    );
    
    protected $prod_stacks = array(
    );
    
    protected $dev_stacks = array(
    );
    
}
